import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * PRD Generator Database Schema
 *
 * Defines the structure for:
 * - users: User authentication and profile data
 * - conversations: Multi-stage PRD creation conversations
 * - prds: Generated Product Requirements Documents
 */
export default defineSchema({
  users: defineTable({
    clerkId: v.string(),
    email: v.string(),
    name: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    createdAt: v.number(),
    lastSeenAt: v.number(),
  }).index("by_clerk_id", ["clerkId"]),
  conversations: defineTable({
    userId: v.string(),
    messages: v.array(
      v.object({
        role: v.union(v.literal("user"), v.literal("assistant")),
        content: v.string(),
        timestamp: v.number(),
      })
    ),
    currentStage: v.union(
      v.literal("setup"),
      v.literal("discovery"),
      v.literal("clarifying"),
      v.literal("researching"),
      v.literal("selecting"),
      v.literal("generating"),
      v.literal("completed"),
      v.literal("tech-stack") // Legacy stage
    ),
    // Legacy fields for backwards compatibility
    prdId: v.optional(v.string()),
    projectName: v.optional(v.string()),
    projectDescription: v.optional(v.string()),
    queriesGenerated: v.optional(v.any()),
    productContext: v.optional(
      v.object({
        productName: v.optional(v.string()),
        description: v.optional(v.string()),
        targetAudience: v.optional(v.string()),
        coreFeatures: v.optional(v.array(v.string())),
      })
    ),
    extractedContext: v.optional(
      v.object({
        productName: v.string(),
        description: v.string(),
        targetAudience: v.string(),
        keyFeatures: v.optional(v.array(v.string())),
        problemStatement: v.string(),
        technicalPreferences: v.optional(v.array(v.string())),
        extractedAt: v.number(),
      })
    ),
    clarifyingQuestions: v.optional(
      v.array(
        v.object({
          id: v.string(),
          category: v.string(),
          question: v.string(),
          placeholder: v.optional(v.string()),
          answer: v.optional(v.string()),
          required: v.boolean(),
          type: v.union(
            v.literal("text"),
            v.literal("textarea"),
            v.literal("select"),
            v.literal("multiselect"), // Legacy type
            v.literal("radio") // Legacy type
          ),
          suggestedOptions: v.optional(v.array(v.string())),
          autoCompleted: v.optional(v.boolean()),
        })
      )
    ),
    answersCompleteness: v.optional(v.number()),
    autoCompletedQuestions: v.optional(v.array(v.string())),
    researchResults: v.optional(v.any()),
    researchAutoGenerated: v.optional(v.boolean()),
    researchMetadata: v.optional(
      v.object({
        startedAt: v.number(),
        completedAt: v.optional(v.number()),
        categoriesCompleted: v.array(v.string()),
        status: v.union(
          v.literal("pending"),
          v.literal("in_progress"),
          v.literal("completed"),
          v.literal("failed")
        ),
      })
    ),
    /**
     * Tech Stack Selection Fields:
     *
     * - `selection`: Auto-selected full stack (used when user skips selection phase)
     *   Simple flat structure with just technology names
     *   Set by: /api/tech-stack/suggest-defaults
     *
     * - `selectedTechStack`: Manual selections with reasoning (used when user reviews options)
     *   Detailed structure with selection reasoning and alternatives considered
     *   Set by: saveSelection mutation when user picks from research results
     *
     * Both fields serve the same purpose but differ in:
     * - Origin: auto vs manual
     * - Detail level: simple vs detailed
     * - When set: skip vs complete workflow
     *
     * PRD generation checks both fields (selection first, then selectedTechStack)
     */
    selection: v.optional(
      v.object({
        frontend: v.string(),
        backend: v.string(),
        database: v.string(),
        auth: v.string(),
        hosting: v.string(),
        autoSelected: v.optional(v.boolean()),
      })
    ),
    selectedTechStack: v.optional(v.any()),
    validationWarnings: v.optional(
      v.array(
        v.object({
          level: v.union(v.literal("warning"), v.literal("error")),
          message: v.string(),
          affectedTechnologies: v.array(v.string()),
          suggestion: v.optional(v.string()),
        })
      )
    ),
    workflowProgress: v.optional(
      v.object({
        currentStep: v.string(), // 'discovery' | 'questions' | 'research' | 'selection' | 'generate'
        completedSteps: v.array(v.string()),
        skippedSteps: v.array(v.string()),
        lastUpdated: v.number(),
      })
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_and_stage", ["userId", "currentStage"]),
  prds: defineTable({
    conversationId: v.id("conversations"),
    userId: v.string(),
    prdData: v.optional(v.any()),
    productName: v.string(),
    version: v.number(),
    status: v.union(v.literal("generating"), v.literal("completed"), v.literal("failed")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_conversation", ["conversationId"])
    .index("by_user_and_created", ["userId", "createdAt"]),
});
