import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * PRD Generator Database Schema
 *
 * Defines the structure for:
 * - users: User authentication and profile data
 * - conversations: Multi-stage PRD creation conversations
 * - prds: Generated Product Requirements Documents
 */
export default defineSchema({
  migrations: defineTable({
    name: v.string(),
    executedAt: v.number(),
    conversationsUpdated: v.number(),
  }).index("by_name", ["name"]),
  users: defineTable({
    clerkId: v.string(),
    email: v.optional(v.string()),
    name: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    createdAt: v.number(),
    lastSeenAt: v.number(),
  }).index("by_clerk_id", ["clerkId"]),
  conversations: defineTable({
    userId: v.string(),
    // Project info set during setup (before discovery)
    projectName: v.optional(v.string()),
    projectDescription: v.optional(v.string()),
    // Link to PRD created during setup
    prdId: v.optional(v.id("prds")),
    messages: v.array(
      v.object({
        role: v.union(v.literal("user"), v.literal("assistant")),
        content: v.string(),
        timestamp: v.number(),
      })
    ),
    currentStage: v.union(
      v.literal("setup"),
      v.literal("discovery"),
      v.literal("clarifying"),
      v.literal("researching"), // deprecated - migrate to tech-stack
      v.literal("selecting"), // deprecated - migrate to tech-stack
      v.literal("tech-stack"),
      v.literal("generating"),
      v.literal("completed")
    ),
    productContext: v.optional(
      v.object({
        productName: v.optional(v.string()),
        description: v.optional(v.string()),
        targetAudience: v.optional(v.string()),
        coreFeatures: v.optional(v.array(v.string())),
      })
    ),
    extractedContext: v.optional(
      v.object({
        productName: v.string(),
        description: v.string(),
        targetAudience: v.string(),
        keyFeatures: v.array(v.string()),
        problemStatement: v.string(),
        technicalPreferences: v.array(v.string()),
        extractedAt: v.number(),
      })
    ),
    clarifyingQuestions: v.optional(
      v.array(
        v.object({
          id: v.string(),
          category: v.string(),
          question: v.string(),
          placeholder: v.optional(v.string()),
          answer: v.optional(v.string()),
          required: v.boolean(),
          type: v.union(v.literal("text"), v.literal("textarea"), v.literal("select"), v.literal("multiselect"), v.literal("radio")),
          suggestedOptions: v.optional(v.array(v.string())),
          autoCompleted: v.optional(v.boolean()),
        })
      )
    ),
    answersCompleteness: v.optional(v.number()),
    autoCompletedQuestions: v.optional(v.array(v.string())),
    // Dynamic tech stack research results - Claude determines which categories are needed
    // Structure: Record<category, { options: TechOption[], reasoning: string }>
    researchResults: v.optional(
      v.record(
        v.string(), // category key
        v.object({
          options: v.array(
            v.object({
              name: v.string(),
              description: v.string(),
              pros: v.array(v.string()),
              cons: v.array(v.string()),
              popularity: v.optional(v.string()),
              learnMore: v.optional(v.string()),
            })
          ),
          reasoning: v.optional(v.string()),
        })
      )
    ),
    // Track which queries were generated for transparency
    queriesGenerated: v.optional(
      v.array(
        v.object({
          category: v.string(),
          reasoning: v.string(),
        })
      )
    ),
    researchAutoGenerated: v.optional(v.boolean()),
    researchMetadata: v.optional(
      v.object({
        startedAt: v.number(),
        completedAt: v.optional(v.number()),
        categoriesCompleted: v.array(v.string()),
        status: v.union(
          v.literal("pending"),
          v.literal("in_progress"),
          v.literal("completed"),
          v.literal("failed")
        ),
      })
    ),
    /**
     * Tech Stack Selection Fields:
     *
     * - `selection`: Auto-selected full stack (used when user skips selection phase)
     *   Simple flat structure with just technology names
     *   Set by: /api/tech-stack/suggest-defaults
     *
     * - `selectedTechStack`: Manual selections with reasoning (used when user reviews options)
     *   Detailed structure with selection reasoning and alternatives considered
     *   Set by: saveSelection mutation when user picks from research results
     *
     * Both fields serve the same purpose but differ in:
     * - Origin: auto vs manual
     * - Detail level: simple vs detailed
     * - When set: skip vs complete workflow
     *
     * PRD generation checks both fields (selection first, then selectedTechStack)
     */
    selection: v.optional(
      v.object({
        frontend: v.string(),
        backend: v.string(),
        database: v.string(),
        auth: v.string(),
        hosting: v.string(),
        autoSelected: v.optional(v.boolean()),
      })
    ),
    selectedTechStack: v.optional(
      v.object({
        frontend: v.optional(
          v.object({
            name: v.string(),
            reasoning: v.string(),
            selectedFrom: v.array(v.string()),
          })
        ),
        backend: v.optional(
          v.object({
            name: v.string(),
            reasoning: v.string(),
            selectedFrom: v.array(v.string()),
          })
        ),
        database: v.optional(
          v.object({
            name: v.string(),
            reasoning: v.string(),
            selectedFrom: v.array(v.string()),
          })
        ),
        authentication: v.optional(
          v.object({
            name: v.string(),
            reasoning: v.string(),
            selectedFrom: v.array(v.string()),
          })
        ),
        hosting: v.optional(
          v.object({
            name: v.string(),
            reasoning: v.string(),
            selectedFrom: v.array(v.string()),
          })
        ),
        real_time_communication: v.optional(
          v.object({
            name: v.string(),
            reasoning: v.string(),
            selectedFrom: v.array(v.string()),
          })
        ),
        file_storage: v.optional(
          v.object({
            name: v.string(),
            reasoning: v.string(),
            selectedFrom: v.array(v.string()),
          })
        ),
        additionalTools: v.optional(
          v.array(
            v.object({
              category: v.string(),
              name: v.string(),
              reasoning: v.string(),
            })
          )
        ),
      })
    ),
    validationWarnings: v.optional(
      v.array(
        v.object({
          level: v.union(v.literal("warning"), v.literal("error")),
          message: v.string(),
          affectedTechnologies: v.array(v.string()),
          suggestion: v.optional(v.string()),
        })
      )
    ),
    workflowProgress: v.optional(
      v.object({
        currentStep: v.union(
          v.literal("discovery"),
          v.literal("questions"),
          v.literal("tech-stack"),
          v.literal("generate")
        ),
        completedSteps: v.array(v.string()),
        skippedSteps: v.array(v.string()),
        lastUpdated: v.number(),
      })
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_and_stage", ["userId", "currentStage"]),
  prds: defineTable({
    conversationId: v.id("conversations"),
    userId: v.string(),
    prdData: v.any(),
    productName: v.string(),
    version: v.number(),
    status: v.union(v.literal("generating"), v.literal("completed"), v.literal("failed")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_conversation", ["conversationId"])
    .index("by_user_and_created", ["userId", "createdAt"]),
});
